const DataFile = {};

DataFile.DifficultyLevel = [
    {value : 'Peaceful', text : 'Peaceful'},
    {value : 'Easy', text : 'Easy'},
    {value : 'Medium', text : 'Medium'},
    {value : 'Rough', text : 'Rough'},
    {value : 'Hard', text : 'Hard'},
    {value : 'Extreme', text : 'Extreme'}
];
DataFile.ArriveModeTypes = [
    {value : "CenterDrop", text : "Center drop"},
    {value : "EdgeWalkIn", text : "Edge walk in"},
    {value : "EdgeDrop", text : "Edge drop"},
    {value : "EdgeWalkInGroups", text : "Edge walk in groups"},
    {value : "EdgeDropGroups", text : "Edge drop groups"},
    {value : "RandomDrop", text : "Random drop"},
];
DataFile.AvailableStats = [
    {value : "AccuracyTouch", text : "Accuracy (close)"},
    {value : "AccuracyShort", text : "Accuracy (short)"},
    {value : "AccuracyMedium", text : "Accuracy (medium)"},
    {value : "AccuracyLong", text : "Accuracy (long)"},
    {value : "AimingDelayFactor", text : "Aiming time"},
    {value : "AnimalGatherSpeed", text : "Animal gather speed"},
    {value : "AnimalGatherYield", text : "Animal gather yield"},
    {value : "StuffEffectMultiplierArmor", text : "Armor - Material effect multiplier"},
    {value : "ArmorRating_Sharp", text : "Armor - Sharp"},
    {value : "ArmorRating_Blunt", text : "Armor - Blunt"},
    {value : "ArmorRating_Heat", text : "Armor - Heat"},
    {value : "StuffPower_Armor_Sharp", text : "Armor - Sharp"},
    {value : "StuffPower_Armor_Blunt", text : "Armor - Blunt"},
    {value : "StuffPower_Armor_Heat", text : "Armor - Heat"},
    {value : "Beauty", text : "Beauty"},
    {value : "BluntDamageMultiplier", text : "Blunt damage"},
    {value : "ButcheryFleshSpeed", text : "Butchery speed"},
    {value : "ButcheryFleshEfficiency", text : "Butchery efficiency"},
    {value : "CarryingCapacity", text : "Carrying capacity"},
    {value : "Cleanliness", text : "Cleanliness"},
    {value : "Comfort", text : "Comfort"},
    {value : "ConstructSuccessChance", text : "Construct success chance"},
    {value : "ConstructionSpeedFactor", text : "Construction speed"},
    {value : "ConstructionSpeed", text : "Construction speed"},
    {value : "CookSpeed", text : "Cooking speed"},
    {value : "RangedWeapon_DamageMultiplier", text : "Damage multiplier"},
    {value : "DeteriorationRate", text : "Deterioration rate"},
    {value : "DoorOpenSpeed", text : "Door opening speed"},
    {value : "DrugSynthesisSpeed", text : "Drug synthesis speed"},
    {value : "DrugCookingSpeed", text : "Drug cooking speed"},
    {value : "EatingSpeed", text : "Eating speed"},
    {value : "EquipDelay", text : "Equip delay"},
    {value : "Flammability", text : "Flammability"},
    {value : "FoodPoisonChanceFixedHuman", text : "Food poison chance"},
    {value : "FoodPoisonChance", text : "Food poison chance"},
    {value : "ForagedNutritionPerDay", text : "Foraged food amount"},
    {value : "GlobalLearningFactor", text : "Global learning factor"},
    {value : "WorkSpeedGlobal", text : "Global work speed"},
    {value : "HungerRateMultiplier", text : "Hunger rate multiplier"},
    {value : "HuntingStealth", text : "Hunting stealth"},
    {value : "ImmunityGainSpeedFactor", text : "Immunity gain speed factor"},
    {value : "ImmunityGainSpeed", text : "Immunity gain speed"},
    {value : "StuffEffectMultiplierInsulation_Cold", text : "Insulation - Cold - Material effect multiplier"},
    {value : "StuffEffectMultiplierInsulation_Heat", text : "Insulation - Heat - Material effect multiplier"},
    {value : "Insulation_Cold", text : "Insulation - Cold"},
    {value : "Insulation_Heat", text : "Insulation - Heat"},
    {value : "StuffPower_Insulation_Cold", text : "Insulation - Cold"},
    {value : "StuffPower_Insulation_Heat", text : "Insulation - Heat"},
    {value : "LeatherAmount", text : "Leather amount"},
    {value : "MarketValue", text : "Market value"},
    {value : "Mass", text : "Mass"},
    {value : "MaxHitPoints", text : "Max hit points"},
    {value : "ComfyTemperatureMax", text : "Maximum comfortable temperature"},
    {value : "MeatAmount", text : "Meat amount"},
    {value : "ButcheryMechanoidSpeed", text : "Mechanoid disassembly speed"},
    {value : "ButcheryMechanoidEfficiency", text : "Mechanoid disassembly efficiency"},
    {value : "MedicalPotency", text : "Medical potency"},
    {value : "MedicalQualityMax", text : "Medical tend quality maximum"},
    {value : "MedicalTendQualityOffset", text : "Medical tend quality offset"},
    {value : "MedicalTendSpeed", text : "Medical tend speed"},
    {value : "MedicalTendQuality", text : "Medical tend quality"},
    {value : "MedicalOperationSpeed", text : "Medical operation speed"},
    {value : "MedicalSurgerySuccessChance", text : "Medical surgery success chance"},
    {value : "MeleeDPS", text : "Melee DPS"},
    {value : "MeleeArmorPenetration", text : "Melee armor penetration"},
    {value : "MeleeHitChance", text : "Melee hit chance"},
    {value : "MeleeDodgeChance", text : "Melee dodge chance"},
    {value : "MeleeWeapon_AverageDPS", text : "Melee damage per second"},
    {value : "MeleeWeapon_AverageArmorPenetration", text : "Melee armor penetration"},
    {value : "MeleeWeapon_DamageMultiplier", text : "Melee damage multiplier"},
    {value : "MeleeWeapon_CooldownMultiplier", text : "Melee cooldown"},
    {value : "MentalBreakThreshold", text : "Mental break threshold"},
    {value : "ComfyTemperatureMin", text : "Minimum comfortable temperature"},
    {value : "MinimumHandlingSkill", text : "Minimum handling skill"},
    {value : "MiningSpeed", text : "Mining speed"},
    {value : "MiningYield", text : "Mining yield"},
    {value : "MoveSpeed", text : "Move speed"},
    {value : "NegotiationAbility", text : "Negotiation ability"},
    {value : "Nutrition", text : "Nutrition"},
    {value : "PainShockThreshold", text : "Pain shock threshold"},
    {value : "PlantWorkSpeed", text : "Plant work speed"},
    {value : "PlantHarvestYield", text : "Plant harvest yield"},
    {value : "PsychicSensitivity", text : "Psychic sensitivity"},
    {value : "RangedWeapon_Cooldown", text : "Ranged cooldown"},
    {value : "JoyGainFactor", text : "Recreation power"},
    {value : "FixBrokenDownBuildingSuccessChance", text : "Repair success chance"},
    {value : "ResearchSpeedFactor", text : "Research speed factor"},
    {value : "ResearchSpeed", text : "Research speed"},
    {value : "BedRestEffectiveness", text : "Rest effectiveness"},
    {value : "RestRateMultiplier", text : "Rest rate multiplier"},
    {value : "SculptingSpeed", text : "Sculpting speed"},
    {value : "SellPriceFactor", text : "Sell price multiplier"},
    {value : "SharpDamageMultiplier", text : "Sharp damage"},
    {value : "EnergyShieldEnergyMax", text : "Shield max energy"},
    {value : "EnergyShieldRechargeRate", text : "Shield recharge rate"},
    {value : "ShootingAccuracyTurret", text : "Shooting accuracy"},
    {value : "ShootingAccuracyPawn", text : "Shooting accuracy"},
    {value : "SmeltingSpeed", text : "Smelting speed"},
    {value : "SmithingSpeed", text : "Smithing speed"},
    {value : "SmokepopBeltRadius", text : "Smokepop belt radius"},
    {value : "SmoothingSpeed", text : "Smoothing speed"},
    {value : "SocialImpact", text : "Social impact"},
    {value : "SurgerySuccessChanceFactor", text : "Surgery success chance factor"},
    {value : "TailoringSpeed", text : "Tailoring speed"},
    {value : "TameAnimalChance", text : "Tame animal chance"},
    {value : "ToxicSensitivity", text : "Toxic sensitivity"},
    {value : "TradePriceImprovement", text : "Trade price improvement"},
    {value : "TrainAnimalChance", text : "Train animal chance"},
    {value : "TrapMeleeDamage", text : "Trap melee damage"},
    {value : "TrapSpringChance", text : "Trap spring chance"},
    {value : "UnskilledLaborSpeed", text : "Unskilled labor speed"},
    {value : "WorkToMake", text : "Work to make"},
    {value : "WorkToBuild", text : "Work to build"},
    {value : "WorkTableWorkSpeedFactor", text : "Work speed factor"},
    {value : "WorkTableEfficiencyFactor", text : "Work efficiency factor"},
];
DataFile.Buildings = [
    {value : "AnimalSleepingSpot", text : "Animal sleeping spot"},
    {value : "AnimalSleepingBox", text : "Animal sleeping box"},
    {value : "AnimalBed", text : "Animal bed"},
    {value : "Armchair", text : "Armchair"},
    {value : "Turret_Autocannon", text : "Autocannon turret"},
    {value : "Autodoor", text : "Autodoor"},
    {value : "Battery", text : "Battery"},
    {value : "Bed", text : "Bed"},
    {value : "Bedroll", text : "Bedroll"},
    {value : "BilliardsTable", text : "Billiards table"},
    {value : "BiofuelRefinery", text : "Biofuel refinery"},
    {value : "Brewery", text : "Brewery"},
    {value : "ButcherSpot", text : "Butcher spot"},
    {value : "TableButcher", text : "Butcher table"},
    {value : "Campfire", text : "Campfire"},
    {value : "CaravanPackingSpot", text : "Caravan packing spot"},
    {value : "ChemfuelPoweredGenerator", text : "Chemfuel powered generator"},
    {value : "ChessTable", text : "Chess table"},
    {value : "CommsConsole", text : "Comms console"},
    {value : "Cooler", text : "Cooler"},
    {value : "CraftingSpot", text : "Crafting spot"},
    {value : "CryptosleepCasket", text : "Cryptosleep casket"},
    {value : "DeepDrill", text : "Deep drill"},
    {value : "DiningChair", text : "Dining chair"},
    {value : "Door", text : "Door"},
    {value : "DoubleSleepingSpot", text : "Double sleeping spot"},
    {value : "DoubleBed", text : "Double bed"},
    {value : "BedrollDouble", text : "Double bedroll"},
    {value : "Dresser", text : "Dresser"},
    {value : "DrugLab", text : "Drug lab"},
    {value : "ElectricTailoringBench", text : "Electric tailor bench"},
    {value : "ElectricSmithy", text : "Electric smithy"},
    {value : "ElectricStove", text : "Electric stove"},
    {value : "ElectricSmelter", text : "Electric smelter"},
    {value : "ElectricCrematorium", text : "Electric crematorium"},
    {value : "EndTable", text : "End table"},
    {value : "FabricationBench", text : "Fabrication bench"},
    {value : "FermentingBarrel", text : "Fermenting barrel"},
    {value : "FirefoamPopper", text : "Firefoam popper"},
    {value : "FlatscreenTelevision", text : "Flatscreen television"},
    {value : "FueledSmithy", text : "Fueled smithy"},
    {value : "FueledStove", text : "Fueled stove"},
    {value : "GameOfUrBoard", text : "Game-of-Ur board"},
    {value : "GeothermalGenerator", text : "Geothermal generator"},
    {value : "Grave", text : "Grave"},
    {value : "GroundPenetratingScanner", text : "Ground-penetrating scanner"},
    {value : "HandTailoringBench", text : "Hand tailor bench"},
    {value : "Heater", text : "Heater"},
    {value : "HiTechResearchBench", text : "Hi-tech research bench"},
    {value : "HoopstoneRing", text : "Hoopstone ring"},
    {value : "Hopper", text : "Hopper"},
    {value : "HorseshoesPin", text : "Horseshoes pin"},
    {value : "HospitalBed", text : "Hospital bed"},
    {value : "HydroponicsBasin", text : "Hydroponics basin"},
    {value : "TrapIED_HighExplosive", text : "IED trap"},
    {value : "TrapIED_Incendiary", text : "IED incendiary trap"},
    {value : "TrapIED_EMP", text : "IED EMP trap"},
    {value : "TrapIED_Firefoam", text : "IED firefoam trap"},
    {value : "TrapIED_AntigrainWarhead", text : "IED antigrain warhead trap"},
    {value : "LongRangeMineralScanner", text : "Long-range mineral scanner"},
    {value : "TableMachining", text : "Machining table"},
    {value : "MarriageSpot", text : "Marriage spot"},
    {value : "Turret_MiniTurret", text : "Mini-turret"},
    {value : "MoisturePump", text : "Moisture pump"},
    {value : "Turret_Mortar", text : "Mortar"},
    {value : "MultiAnalyzer", text : "Multi-analyzer"},
    {value : "NutrientPasteDispenser", text : "Nutrient paste dispenser"},
    {value : "OrbitalTradeBeacon", text : "Orbital trade beacon"},
    {value : "PartySpot", text : "Party spot"},
    {value : "PassiveCooler", text : "Passive cooler"},
    {value : "PlantPot", text : "Plant pot"},
    {value : "PodLauncher", text : "Pod launcher"},
    {value : "PokerTable", text : "Poker table"},
    {value : "PowerConduit", text : "Power conduit"},
    {value : "PowerSwitch", text : "Power switch"},
    {value : "RoyalBed", text : "Royal bed"},
    {value : "Sandbags", text : "Sandbags"},
    {value : "Sarcophagus", text : "Sarcophagus"},
    {value : "TableSculpting", text : "Sculptor's table"},
    {value : "Ship_SensorCluster", text : "Sensor cluster"},
    {value : "Shelf", text : "Shelf"},
    {value : "Ship_Beam", text : "Ship structural beam"},
    {value : "Ship_CryptosleepCasket", text : "Ship cryptosleep casket"},
    {value : "Ship_ComputerCore", text : "Ship computer core"},
    {value : "Ship_Reactor", text : "Ship reactor"},
    {value : "Ship_Engine", text : "Ship engine"},
    {value : "SimpleResearchBench", text : "Simple research bench"},
    {value : "SleepingSpot", text : "Sleeping spot"},
    {value : "SolarGenerator", text : "Solar generator"},
    {value : "TrapSpike", text : "Spike trap"},
    {value : "StandingLamp", text : "Standing lamp"},
    {value : "StandingLamp_Red", text : "Standing lamp (red)"},
    {value : "StandingLamp_Green", text : "Standing lamp (green)"},
    {value : "StandingLamp_Blue", text : "Standing lamp (blue)"},
    {value : "TableStonecutter", text : "Stonecutter's table"},
    {value : "Stool", text : "Stool"},
    {value : "SunLamp", text : "Sun lamp"},
    {value : "Table1x2c", text : "Table (1x2)"},
    {value : "Table2x2c", text : "Table (2x2)"},
    {value : "Table2x4c", text : "Table (2x4)"},
    {value : "Table3x3c", text : "Table (3x3)"},
    {value : "ToolCabinet", text : "Tool cabinet"},
    {value : "TorchLamp", text : "Torch lamp"},
    {value : "TransportPod", text : "Transport pod"},
    {value : "TubeTelevision", text : "Tube television"},
    {value : "Turret_Sniper", text : "Uranium slug turret"},
    {value : "Vent", text : "Vent"},
    {value : "VitalsMonitor", text : "Vitals monitor"},
    {value : "Wall", text : "Wall"},
    {value : "WatermillGenerator", text : "Watermill generator"},
    {value : "WaterproofConduit", text : "Waterproof conduit"},
    {value : "WindTurbine", text : "Wind turbine"},
    {value : "WoodFiredGenerator", text : "Wood-fired generator"},
];
DataFile.StrategyTypes = [
    {value : "ImmediateAttack", text : "Immediate attack"},
    {value : "ImmediateAttackSmart", text : "Immediate attack smart"},
    {value : "ImmediateAttackSappers", text : "Immediate attack sappers"},
    {value : "Siege", text : "Siege"},
    {value : "StageThenAttack", text : "Preparing then attack"},
];
DataFile.BodyParts = [
    {value : "AnimalJaw", text : "Animal jaw"},
    {value : "Antenna", text : "Antenna"},
    {value : "Arm", text : "Arm"},
    {value : "ArtificialBrain", text : "Artificial brain"},
    {value : "Beak", text : "Beak"},
    {value : "Body", text : "Body"},
    {value : "Brain", text : "Brain"},
    {value : "SmellSensor", text : "Chemical analyzer"},
    {value : "Clavicle", text : "Clavicle"},
    {value : "Ear", text : "Ear"},
    {value : "Elytra", text : "Elytra"},
    {value : "Eye", text : "Eye"},
    {value : "Femur", text : "Femur"},
    {value : "Finger", text : "Finger"},
    {value : "FluidReprocessor", text : "Fluid reprocessor"},
    {value : "Foot", text : "Foot"},
    {value : "FrontClaw", text : "Front claw"},
    {value : "Hand", text : "Hand"},
    {value : "Head", text : "Head"},
    {value : "HeadClaw", text : "Head claw"},
    {value : "Hoof", text : "Hoof"},
    {value : "Horn", text : "Horn"},
    {value : "Humerus", text : "Humerus"},
    {value : "Hump", text : "Hump"},
    {value : "InsectLeg", text : "Insect leg"},
    {value : "InsectHead", text : "Insect head"},
    {value : "InsectHeart", text : "Insect heart"},
    {value : "InsectNostril", text : "Insect nostril"},
    {value : "InsectMouth", text : "Insect mouth"},
    {value : "Jaw", text : "Jaw"},
    {value : "Jowl", text : "Jowl"},
    {value : "Leg", text : "Leg"},
    {value : "MechanicalNeck", text : "Mechanical neck"},
    {value : "MechanicalHead", text : "Mechanical head"},
    {value : "MechanicalShoulder", text : "Mechanical shoulder"},
    {value : "Neck", text : "Neck"},
    {value : "Nose", text : "Nose"},
    {value : "Paw", text : "Paw"},
    {value : "Pelvis", text : "Pelvis"},
    {value : "Plastron", text : "Plastron"},
    {value : "Pronotum", text : "Pronotum"},
    {value : "Radius", text : "Radius"},
    {value : "Reactor", text : "Reactor"},
    {value : "RearClaw", text : "Rear claw"},
    {value : "Ribcage", text : "Ribcage"},
    {value : "Shell", text : "Shell"},
    {value : "TurtleShell", text : "Shell"},
    {value : "Shoulder", text : "Shoulder"},
    {value : "Skull", text : "Skull"},
    {value : "SnakeBody", text : "Snake body"},
    {value : "SnakeHead", text : "Snake head"},
    {value : "SnakeMouth", text : "Snake mouth"},
    {value : "HearingSensor", text : "Sound sensor"},
    {value : "Spine", text : "Spine"},
    {value : "Sternum", text : "Sternum"},
    {value : "Tail", text : "Tail"},
    {value : "Tibia", text : "Tibia"},
    {value : "Toe", text : "Toe"},
    {value : "Torso", text : "Torso"},
    {value : "Trunk", text : "Trunk"},
    {value : "TurtleBeak", text : "Turtle beak"},
    {value : "Tusk", text : "Tusk"},
    {value : "SightSensor", text : "Visual sensor"},
    {value : "Waist", text : "Waist"},
];
DataFile.MentalBreakTypes = [
    {value : "BedroomTantrum", text : "Bedroom tantrum"},
    {value : "Berserk", text : "Berserk"},
    {value : "Binging_Food", text : "Binging food"},
    {value : "Catatonic", text : "Catatonic"},
    {value : "CorpseObsession", text : "Corpse obsession"},
    {value : "GiveUpExit", text : "Give up (to exit)"},
    {value : "InsultingSpree", text : "Insulting spree"},
    {value : "Jailbreaker", text : "Jailbreaker"},
    {value : "MurderousRage", text : "Murderous rage"},
    {value : "RunWild", text : "Run wild"},
    {value : "SadisticRage", text : "Sadistic tage"},
    {value : "Slaughterer", text : "Slaughterer"},
    {value : "FireStartingSpree", text : "Starting fire spree"},
    {value : "Tantrum", text : "Tantrum"},
    {value : "TargetedTantrum", text : "Targeted tantrum"},
    {value : "TargetedInsultingSpree", text : "Targeted insulting spree"},
    {value : "Wander_Psychotic", text : "Wander - Psychotic"},
    {value : "Wander_Sad", text : "Wander - Sad"},
    {value : "Wander_OwnRoom", text : "Wander - Own room"},
];
DataFile.HealthActions = [
    {value : "Anesthetize", text : "Anesthetize"},
    {value : "DamageTillDowned", text : "Damage till downed"},
    {value : "Immobilize", text : "Damage till immobilize"},
    {value : "PsychicShock", text : "Psychic shock"},
    {value : "MissingBodyPart", text : "Remove body part"},
    {value : "StabBodyPart", text : "Stab body part"},
];
DataFile.IntentTypes = [
    {value : "AssaultColony", text : "Assault colony"},
    {value : "AssistColony", text : "Assist colony"},
    {value : "Capture", text : "Capture"},
    {value : "DefendAttackedTraderCaravan", text : "Defend attacked trader (must be trader in name group)"},
    {value : "DefendAndExpandHive", text : "Defend and expand hive"},
    {value : "DefendBase", text : "Defend base"},
    {value : "DefendPoint", text : "Defend point"},
    {value : "ExitMapBest", text : "Exit map"},
    {value : "Follow", text : "Follow pawn"},
    {value : "FollowClose", text : "Move to pawn closely"},
    {value : "Hunt", text : "Hunt pawn"},
    {value : "Ignite", text : "Ignite ( does not start a fire ): )"},
    {value : "Insult", text : "Insult"},
    {value : "Kidnap", text : "Kidnap / carry pawn to exit"},
    {value : "LayDown", text : "LayDown"},
    {value : "ManTurrets", text : "Man available turrets"},
    {value : "Joinable_MarriageCeremony", text : "Marriage ceremony (names are guests)"},
    {value : "AttackMelee", text : "Melee attack"},
    {value : "Joinable_Party", text : "Party"},
    {value : "PrisonBreak", text : "Prison break"},
    {value : "PrisonerExecution", text : "Prisoner execution"},
    {value : "AttackStatic", text : "Range attack"},
    {value : "ReleasePrisoner", text : "Release prisoner"},
    {value : "Rescue", text : "Rescue"},
    {value : "Siege", text : "Siege (also spawns resources & blueprints)"},
    {value : "Slaughter", text : "Slaughter"},
    {value : "SleepThenAssaultColony", text : "Sleep, assault if to close"},
    {value : "StageThenAttack", text : "Stage then attack (prepare)"},
    {value : "Steal", text : "Steal"},
    {value : "Strip", text : "Strip pawn"},
    {value : "TradeWithColony", text : "Trade with colony (only walks to colony edge)"},
    {value : "TradeWithPawn", text : "Trade with pawn"},
    {value : "TravelAndExit", text : "Travel to point then exit"},
    {value : "Travel", text : "Travel to point (can be used with condition 'Traveled')"},
    {value : "UnloadYourInventory", text : "Unload all inventory"},
    {value : "VisitColony", text : "Visit colony"},
    {value : "Vomit", text : "Vomit"},
    {value : "Wait", text : "Wait / clear queue"},
];
DataFile.SystemVariables = [
    "_DAYS",
    "_TREAT_POINTS",
    "_WEALTH"
];
DataFile.ResearchProject = [
    {value : "AdvancedFabrication", text : "Advanced fabrication"},
    {value : "ShipComputerCore", text : "AI persuasion"},
    {value : "AirConditioning", text : "Air conditioning"},
    {value : "HeavyTurrets", text : "Autocannon turret"},
    {value : "Autodoors", text : "Autodoor"},
    {value : "Batteries", text : "Battery"},
    {value : "Brewing", text : "Beer brewing"},
    {value : "BiofuelRefining", text : "Biofuel refining"},
    {value : "Bionics", text : "Bionics"},
    {value : "BlowbackOperation", text : "Blowback operation"},
    {value : "CarpetMaking", text : "Carpet making"},
    {value : "Cocoa", text : "Cocoa"},
    {value : "ColoredLights", text : "Colored lights"},
    {value : "ComplexFurniture", text : "Complex furniture"},
    {value : "ComplexClothing", text : "Complex clothing"},
    {value : "Cryptosleep", text : "Cryptosleep casket"},
    {value : "DeepDrilling", text : "Deep drilling"},
    {value : "Devilstrand", text : "Devilstrand"},
    {value : "DrugProduction", text : "Drug production"},
    {value : "Electricity", text : "Electricity"},
    {value : "Fabrication", text : "Fabrication"},
    {value : "Firefoam", text : "Firefoam"},
    {value : "FlakArmor", text : "Flak armor"},
    {value : "FlatscreenTelevision", text : "Flatscreen television"},
    {value : "GasOperation", text : "Gas operation"},
    {value : "GeothermalPower", text : "Geothermal power"},
    {value : "GoJuiceProduction", text : "Go-juice production"},
    {value : "Greatbow", text : "Greatbow"},
    {value : "GroundPenetratingScanner", text : "Ground-penetrating scanner"},
    {value : "GunTurrets", text : "Gun turrets"},
    {value : "Gunsmithing", text : "Gunsmithing"},
    {value : "HospitalBed", text : "Hospital bed"},
    {value : "Hydroponics", text : "Hydroponics"},
    {value : "IEDs", text : "IEDs"},
    {value : "ShipEngine", text : "Johnson-Tanaka drive"},
    {value : "LongRangeMineralScanner", text : "Long-range mineral scanner"},
    {value : "LongBlades", text : "Long blades"},
    {value : "Machining", text : "Machining"},
    {value : "MedicineProduction", text : "Medicine production"},
    {value : "MicroelectronicsBasics", text : "Microelectronics"},
    {value : "MoisturePump", text : "Moisture pump"},
    {value : "Mortars", text : "Mortars"},
    {value : "MultiAnalyzer", text : "Multi-analyzer"},
    {value : "MultibarrelWeapons", text : "Multibarrel weapons"},
    {value : "NutrientPaste", text : "Nutrient paste"},
    {value : "PackagedSurvivalMeal", text : "Packaged survival meal"},
    {value : "PassiveCooler", text : "Passive cooler"},
    {value : "Pemmican", text : "Pemmican"},
    {value : "PenoxycylineProduction", text : "Penoxycyline production"},
    {value : "PlateArmor", text : "Plate armor"},
    {value : "PoweredArmor", text : "Powered armor"},
    {value : "PrecisionRifling", text : "Precision rifling"},
    {value : "Prosthetics", text : "Prosthetics"},
    {value : "PsychiteRefining", text : "Psychite refining"},
    {value : "PsychoidBrewing", text : "Psychoid brewing"},
    {value : "ChargedShot", text : "Pulse-charged munitions"},
    {value : "RecurveBow", text : "Recurve bow"},
    {value : "ShieldBelt", text : "Shield belt"},
    {value : "Smithing", text : "Smithing"},
    {value : "SmokepopBelt", text : "Smokepop belts"},
    {value : "SolarPanels", text : "Solar panel"},
    {value : "ShipBasics", text : "Starflight basics"},
    {value : "ShipSensorCluster", text : "Starflight sensors"},
    {value : "ShipReactor", text : "Starship reactor"},
    {value : "SterileMaterials", text : "Sterile materials"},
    {value : "Stonecutting", text : "Stonecutting"},
    {value : "TransportPod", text : "Transport pod"},
    {value : "TreeSowing", text : "Tree sowing"},
    {value : "TubeTelevision", text : "Tube television"},
    {value : "SniperTurret", text : "Uranium slug turret"},
    {value : "ShipCryptosleep", text : "Vacuum cryptosleep casket"},
    {value : "VitalsMonitor", text : "Vitals monitor"},
    {value : "WakeUpProduction", text : "Wake-up production"},
    {value : "WatermillGenerator", text : "Watermill generator"},
];
DataFile.ItemQualities = [
    {value : 'Awful', text : 'Awful'},
    {value : 'Poor', text : 'Poor'},
    {value : 'Normal', text : 'Normal'},
    {value : 'Good', text : 'Good'},
    {value : 'Excellent', text : 'Excellent'},
    {value : 'Masterwork', text : 'Masterwork'}
];
DataFile.Stuff = [
    {value : 'WoolAlpaca', text : 'Alpaca wool'},
    {value : 'Leather_Bear', text : 'Bearskin'},
    {value : 'Leather_Bird', text : 'Birdskin'},
    {value : 'Leather_Bluefur', text : 'Bluefur'},
    {value : 'WoolCamel', text : 'Camelhair'},
    {value : 'Leather_Camel', text : 'Camelhide'},
    {value : 'Leather_Chinchilla', text : 'Chinchilla fur'},
    {value : 'Cloth', text : 'Cloth'},
    {value : 'DevilstrandCloth', text : 'Devilstrand'},
    {value : 'Leather_Dog', text : 'Dog leather'},
    {value : 'Leather_Elephant', text : 'Elephant leather'},
    {value : 'Leather_Fox', text : 'Foxfur'},
    {value : 'Gold', text : 'Gold'},
    {value : 'BlocksGranite', text : 'Granite blocks'},
    {value : 'Leather_Heavy', text : 'Heavy fur'},
    {value : 'Leather_Human', text : 'Human leather'},
    {value : 'Hyperweave', text : 'Hyperweave'},
    {value : 'Jade', text : 'Jade'},
    {value : 'Leather_Light', text : 'Lightleather'},
    {value : 'BlocksLimestone', text : 'Limestone blocks'},
    {value : 'Leather_Lizard', text : 'Lizardskin'},
    {value : 'BlocksMarble', text : 'Marble blocks'},
    {value : 'WoolMegasloth', text : 'Megasloth wool'},
    {value : 'WoolMuffalo', text : 'Muffalo wool'},
    {value : 'Leather_Panthera', text : 'Panthera fur'},
    {value : 'Leather_Patch', text : 'Patchleather'},
    {value : 'Leather_Pig', text : 'Pigskin'},
    {value : 'Leather_Plain', text : 'Plainleather'},
    {value : 'Plasteel', text : 'Plasteel'},
    {value : 'Leather_Rhinoceros', text : 'Rhinoceros leather'},
    {value : 'BlocksSandstone', text : 'Sandstone blocks'},
    {value : 'Silver', text : 'Silver'},
    {value : 'BlocksSlate', text : 'Slate blocks'},
    {value : 'Steel', text : 'Steel'},
    {value : 'Synthread', text : 'Synthread'},
    {value : 'Leather_Thrumbo', text : 'Thrumbofur'},
    {value : 'Uranium', text : 'Uranium'},
    {value : 'Leather_Wolf', text : 'Wolfskin'},
    {value : 'WoodLog', text : 'Wood'},
];
DataFile.ShipParts = [
    {value : 'CrashedPsychicEmanatorShipPart', text : 'Mechanoid ship part (Emanator)'},
    {value : 'CrashedPoisonShipPart', text : 'Mechanoid ship part (Poison)'},
    {value : 'ShipChunk', text : 'Ship chunk (metal)'},
];
DataFile.Positions = [
    {value : 'Random', text : 'Random'},
    {value : 'RandomEdge', text : 'Random edge'},
    {value : 'Center', text : 'Map center'},
    {value : 'OutsideColony', text : 'Just outside colony'},
    {value : 'Siege', text : 'Siege location'},
    {value : 'Pointer', text : 'Mouse pointer'},
];
DataFile.MineableMaterials = [
    {value : 'MineableSteel', text : 'Mineable steel'},
    {value : 'MineableSilver', text : 'Mineable silver'},
    {value : 'MineableGold', text : 'Mineable gold'},
    {value : 'MineableUranium', text : 'Mineable uranium'},
    {value : 'MineablePlasteel', text : 'Mineable plasteel'},
    {value : 'MineableJade', text : 'Mineable jade'},
    {value : 'MineableComponentsIndustrial', text : 'Mineable components'},
    {value : 'Sandstone', text : 'Sandstone'},
    {value : 'Granite', text : 'Granite'},
    {value : 'Limestone', text : 'Limestone'},
    {value : 'Slate', text : 'Slate'},
    {value : 'Marble', text : 'Marble'}
];
DataFile.PawnKind = [
    {value : 'Alpaca', text : 'Alpaca'},
    {value : 'Alphabeaver', text : 'Alphabeaver'},
    {value : 'AncientSoldier', text : 'Ancient soldier'},
    {value : 'Tribal_Archer', text : 'Archer'},
    {value : 'Tribal_ChiefRanged', text : 'Archer chief'},
    {value : 'Wolf_Arctic', text : 'Arctic wolf'},
    {value : 'Fox_Arctic', text : 'Arctic fox'},
    {value : 'Tribal_Berserker', text : 'Berserker'},
    {value : 'Tribal_ChiefMelee', text : 'Berserker chief'},
    {value : 'Boomalope', text : 'Boomalope'},
    {value : 'Boomrat', text : 'Boomrat'},
    {value : 'PirateBoss', text : 'Boss'},
    {value : 'Capybara', text : 'Capybara'},
    {value : 'Caribou', text : 'Caribou'},
    {value : 'Cassowary', text : 'Cassowary'},
    {value : 'Cat', text : 'Cat'},
    {value : 'Mech_Centipede', text : 'Centipede'},
    {value : 'Chicken', text : 'Chicken'},
    {value : 'Chinchilla', text : 'Chinchilla'},
    {value : 'Cobra', text : 'Cobra'},
    {value : 'Colonist', text : 'Colonist'},
    {value : 'Cougar', text : 'Cougar'},
    {value : 'Cow', text : 'Cow'},
    {value : 'Deer', text : 'Deer'},
    {value : 'Drifter', text : 'Drifter'},
    {value : 'Dromedary', text : 'Dromedary'},
    {value : 'Elephant', text : 'Elephant'},
    {value : 'Mercenary_Elite', text : 'Elite mercenary'},
    {value : 'Elk', text : 'Elk'},
    {value : 'Grenadier_EMP', text : 'EMP grenadier'},
    {value : 'Emu', text : 'Emu'},
    {value : 'Fox_Fennec', text : 'Fennec fox'},
    {value : 'Gazelle', text : 'Gazelle'},
    {value : 'Grenadier_Destructive', text : 'Grenadier'},
    {value : 'Bear_Grizzly', text : 'Grizzly bear'},
    {value : 'Hare', text : 'Hare'},
    {value : 'Mercenary_Heavy', text : 'Heavy mercenary'},
    {value : 'Tribal_HeavyArcher', text : 'Heavy archer'},
    {value : 'Tribal_Hunter', text : 'Hunter'},
    {value : 'Husky', text : 'Husky'},
    {value : 'Ibex', text : 'Ibex'},
    {value : 'Iguana', text : 'Iguana'},
    {value : 'LabradorRetriever', text : 'Labrador retriever'},
    {value : 'Mech_Lancer', text : 'Lancer'},
    {value : 'Lynx', text : 'Lynx'},
    {value : 'Megascarab', text : 'Megascarab'},
    {value : 'Megasloth', text : 'Megasloth'},
    {value : 'Megaspider', text : 'Megaspider'},
    {value : 'Tribesperson', text : 'Member'},
    {value : 'Mercenary_Gunner', text : 'Mercenary gunner'},
    {value : 'Mercenary_Sniper', text : 'Mercenary sniper'},
    {value : 'Mercenary_Slasher', text : 'Mercenary slasher'},
    {value : 'Monkey', text : 'Monkey'},
    {value : 'Muffalo', text : 'Muffalo'},
    {value : 'Ostrich', text : 'Ostrich'},
    {value : 'Panther', text : 'Panther'},
    {value : 'Tribal_Penitent', text : 'Penitent'},
    {value : 'Pig', text : 'Pig'},
    {value : 'Pirate', text : 'Pirate gunner'},
    {value : 'Bear_Polar', text : 'Polar bear'},
    {value : 'Raccoon', text : 'Raccoon'},
    {value : 'Rat', text : 'Rat'},
    {value : 'Fox_Red', text : 'Red fox'},
    {value : 'Rhinoceros', text : 'Rhinoceros'},
    {value : 'Scavenger', text : 'Scavenger gunner'},
    {value : 'Thrasher', text : 'Scavenger thrasher'},
    {value : 'Mech_Scyther', text : 'Scyther'},
    {value : 'Slave', text : 'Slave'},
    {value : 'Snowhare', text : 'Snowhare'},
    {value : 'SpaceRefugee', text : 'Space refugee'},
    {value : 'Spelopede', text : 'Spelopede'},
    {value : 'Squirrel', text : 'Squirrel'},
    {value : 'StrangerInBlack', text : 'Stranger in black'},
    {value : 'Thrumbo', text : 'Thrumbo'},
    {value : 'Wolf_Timber', text : 'Timber wolf'},
    {value : 'Tortoise', text : 'Tortoise'},
    {value : 'Town_Guard', text : 'Town guard'},
    {value : 'Town_Trader', text : 'Town trader'},
    {value : 'Town_Councilman', text : 'Town councilman'},
    {value : 'Tribal_Trader', text : 'Trader'},
    {value : 'Turkey', text : 'Turkey'},
    {value : 'Villager', text : 'Villager'},
    {value : 'Warg', text : 'Warg'},
    {value : 'Tribal_Warrior', text : 'Warrior'},
    {value : 'WildMan', text : 'Wild man'},
    {value : 'WildBoar', text : 'Wild boar'},
    {value : 'YorkshireTerrier', text : 'Yorkshire terrier'},
];
DataFile.Factions = [
    {value: "Ancients", text: "Ancients"},
    {value: "AncientsHostile", text: "Ancients Hostile"},
    {value: "Insect", text: "Insect"},
    {value: "Mechanoid", text: "Mechanoid"},
    {value: "OutlanderCivil", text: "Outlander Civil"},
    {value: "OutlanderRough", text: "Outlander Rough"},
    {value: "Pirate", text: "Pirate"},
    {value: "PlayerColony", text: "Player Colony"},
    {value: "TribeCivil", text: "Tribe Civil"},
    {value: "TribeRough", text: "Tribe Rough"},
];
DataFile.SiteTypes = [
    {value : "Base", text : "Base"},
    {value : "Encounter", text : "Encounter (empty)"},
    {value : "SpaceShip", text : "Space ship"}
];
DataFile.DiseaseTypes = [
    {value : 'Disease_AnimalFlu', text : 'Animal Flu'},
    {value : 'Disease_AnimalPlague', text : 'Animal Plague'},
    {value : 'Disease_FibrousMechanites', text : 'Fibrous Mechanites'},
    {value : 'Disease_Flu', text : 'Flu'},
    {value : 'Disease_GutWorms', text : 'Gut Worms'},
    {value : 'Disease_Malaria', text : 'Malaria'},
    {value : 'Disease_MuscleParasites', text : 'Muscle Parasites'},
    {value : 'Disease_Plague', text : 'Plague'},
    {value : 'Disease_SensoryMechanites', text : 'Sensory Mechanites'},
    {value : 'Disease_SleepingSickness', text : 'Sleeping Sickness'},
];
DataFile.Biomes = [
    {value : 'AridShrubland', text : 'Arid shrubland'},
    {value : 'BorealForest', text : 'Boreal forest'},
    {value : 'ColdBog', text : 'Cold bog'},
    {value : 'Desert', text : 'Desert'},
    {value : 'ExtremeDesert', text : 'Extreme desert'},
    {value : 'IceSheet', text : 'Ice sheet'},
    {value : 'Lake', text : 'Lake'},
    {value : 'Ocean', text : 'Ocean'},
    {value : 'SeaIce', text : 'Sea ice'},
    {value : 'TemperateForest', text : 'Temperate forest'},
    {value : 'TemperateSwamp', text : 'Temperate swamp'},
    {value : 'TropicalRainforest', text : 'Tropical rainforest'},
    {value : 'TropicalSwamp', text : 'Tropical swamp'},
    {value : 'Tundra', text : 'Tundra'},
];
DataFile.Weapons = [
    {value : 'None', text : 'none'},
    {value : 'Gun_AssaultRifle', text : 'Assault rifle'},
    {value : 'Gun_AutocannonTurret', text : 'Autocannon'},
    {value : 'Gun_Autopistol', text : 'Autopistol'},
    {value : 'Beer', text : 'Beer'},
    {value : 'Gun_BoltActionRifle', text : 'Bolt-action rifle'},
    {value : 'Gun_ChainShotgun', text : 'Chain shotgun'},
    {value : 'Gun_ChargeRifle', text : 'Charge rifle'},
    {value : 'Gun_ChargeLance', text : 'Charge lance'},
    {value : 'MeleeWeapon_Club', text : 'Club'},
    {value : 'Gun_DoomsdayRocket', text : 'Doomsday rocket launcher'},
    {value : 'ElephantTusk', text : 'Elephant tusk'},
    {value : 'Weapon_GrenadeEMP', text : 'EMP grenades'},
    {value : 'Weapon_GrenadeFrag', text : 'Frag grenades'},
    {value : 'MeleeWeapon_Gladius', text : 'Gladius'},
    {value : 'Bow_Great', text : 'Greatbow'},
    {value : 'Gun_HeavySMG', text : 'Heavy SMG'},
    {value : 'Gun_ChargeBlasterHeavy', text : 'Heavy charge blaster'},
    {value : 'MeleeWeapon_Ikwa', text : 'Ikwa'},
    {value : 'Gun_IncendiaryLauncher', text : 'Incendiary launcher'},
    {value : 'Gun_InfernoCannon', text : 'Inferno cannon'},
    {value : 'MeleeWeapon_Knife', text : 'Knife'},
    {value : 'Gun_LMG', text : 'LMG'},
    {value : 'MeleeWeapon_LongSword', text : 'Longsword'},
    {value : 'MeleeWeapon_Mace', text : 'Mace'},
    {value : 'Gun_MachinePistol', text : 'Machine pistol'},
    {value : 'Gun_MiniTurret', text : 'Mini-turret gun'},
    {value : 'Gun_Minigun', text : 'Minigun'},
    {value : 'Weapon_GrenadeMolotov', text : 'Molotov cocktails'},
    {value : 'Artillery_Mortar', text : 'Mortar'},
    {value : 'OrbitalTargeterBombardment', text : 'Orbital bombardment targeter'},
    {value : 'OrbitalTargeterPowerBeam', text : 'Orbital power beam targeter'},
    {value : 'Pila', text : 'Pila'},
    {value : 'Gun_PumpShotgun', text : 'Pump shotgun'},
    {value : 'Bow_Recurve', text : 'Recurve bow'},
    {value : 'Gun_Revolver', text : 'Revolver'},
    {value : 'Bow_Short', text : 'Short bow'},
    {value : 'Gun_SniperRifle', text : 'Sniper rifle'},
    {value : 'MeleeWeapon_Spear', text : 'Spear'},
    {value : 'ThrumboHorn', text : 'Thrumbo horn'},
    {value : 'TornadoGenerator', text : 'Tornado generator'},
    {value : 'Gun_TripleRocket', text : 'Triple rocket launcher'},
    {value : 'Gun_TurretSniper', text : 'Uranium slug cannon'},
    {value : 'WoodLog', text : 'Wood'},
];
DataFile.Traders = [
    {value : 'Caravan_Neolithic_BulkGoods', text : 'Caravan Neolithic Bulk goods'},
    {value : 'Caravan_Neolithic_ShamanMerchant', text : 'Caravan Neolithic Shaman merchant'},
    {value : 'Caravan_Neolithic_Slaver', text : 'Caravan Neolithic Slaver'},
    {value : 'Caravan_Neolithic_WarMerchant', text : 'Caravan Neolithic War merchant'},
    {value : 'Caravan_Outlander_BulkGoods', text : 'Caravan Outlander Bulk goods'},
    {value : 'Caravan_Outlander_CombatSupplier', text : 'Caravan Outlander Combat supplier'},
    {value : 'Caravan_Outlander_Exotic', text : 'Caravan Outlander Exotic'},
    {value : 'Caravan_Outlander_PirateMerchant', text : 'Caravan Outlander Pirate merchant'},
    {value : 'Orbital_BulkGoods', text : 'Orbital Bulk goods'},
    {value : 'Orbital_CombatSupplier', text : 'Orbital Combat supplier'},
    {value : 'Orbital_Exotic', text : 'Orbital Exotic'},
    {value : 'Orbital_PirateMerchant', text : 'Orbital Pirate merchant'},
    {value : 'Visitor_Neolithic_Standard', text : 'Visitor Neolithic Standard'},
    {value : 'Visitor_Outlander_Standard', text : 'Visitor Outlander Standard'}
];
DataFile.ExplosionTypes = [
    {value: "Bomb", text: "Bomb"},
    {value: "BombSuper", text: "Super bomb"},
    {value: "Smoke", text: "Smoke"},
    {value: "Flame", text: "Flame"},
    {value: "Stun", text: "Stun"},
    {value: "EMP", text: "EMP"},
];
DataFile.ThoughtTypes = [
    {value : "custom", text : "*Custom*"},
    {value : "BondedAnimalMaster", text : "{0}'s master"},
    {value : "KnowPrisonerSold", text : "A prisoner was sold"},
    {value : "Affair", text : "Affair"},
    {value : "Inebriated", text : "Alcohol warmth"},
    {value : "AlcoholWithdrawal", text : "Alcohol withdrawal"},
    {value : "AmbrosiaHigh", text : "Ambrosia warmth"},
    {value : "AmbrosiaWithdrawal", text : "Ambrosia withdrawal"},
    {value : "HadAngeringFight", text : "Angering fight"},
    {value : "AnnoyingVoice", text : "Annoying voice"},
    {value : "Ascetic", text : "Ascetic has awful bedroom"},
    {value : "AteLavishMeal", text : "Ate lavish meal"},
    {value : "AteFineMeal", text : "Ate fine meal"},
    {value : "AteAwfulMeal", text : "Ate awful meal"},
    {value : "AteRawFood", text : "Ate raw food"},
    {value : "AteKibble", text : "Ate kibble"},
    {value : "AteCorpse", text : "Ate corpse"},
    {value : "AteInsectMeatDirect", text : "Ate insect meat"},
    {value : "AteInsectMeatAsIngredient", text : "Ate cooked insect meat"},
    {value : "AteRottenFood", text : "Ate rotten food"},
    {value : "AteWithoutTable", text : "Ate without table"},
    {value : "AteRawHumanlikeMeat", text : "Ate raw humanlike meat"},
    {value : "AttendedWedding", text : "Attended wedding"},
    {value : "AttendedParty", text : "Attended party"},
    {value : "SleptInBedroom", text : "Awful bedroom"},
    {value : "SleptInBarracks", text : "Awful barrack"},
    {value : "PrisonCell", text : "Awful prison cell"},
    {value : "PrisonBarracks", text : "Awful barrack"},
    {value : "HospitalPatientRoomStats", text : "Awful hospital"},
    {value : "Aurora", text : "Beautiful aurora"},
    {value : "BodyPuristDisgust", text : "Body purist disgust"},
    {value : "ProsthophobeUnhappy", text : "Body purist squeamish"},
    {value : "BondedAnimalDied", text : "Bonded animal {0} died"},
    {value : "BondedAnimalBanished", text : "Bonded animal {0} banished"},
    {value : "SoldMyBondedAnimal", text : "Bonded animal sold"},
    {value : "BotchedMySurgery", text : "Botched my surgery"},
    {value : "BrawlerUnhappy", text : "Brawler has ranged weapon"},
    {value : "BrokeUpWithMe", text : "Broke up with me"},
    {value : "BrokeUpWithMeMood", text : "Broken up with by {0}"},
    {value : "KnowBuriedInSarcophagus", text : "Buried in sarcophagus"},
    {value : "ButcheredHumanlikeCorpseOpinion", text : "Butchered humanlike corpse"},
    {value : "Catharsis", text : "Catharsis"},
    {value : "HadCatharticFight", text : "Cathartic fight"},
    {value : "CheatedOnMe", text : "Cheated on me"},
    {value : "CheatedOnMeMood", text : "Cheated on by {0}"},
    {value : "ChemicalInterestVsTeetotaler", text : "Chemical interest vs teetotaler"},
    {value : "EnvironmentCold", text : "Chilly"},
    {value : "Chitchat", text : "Chitchat"},
    {value : "KnowColonistOrganHarvested", text : "Colonist's organ harvested"},
    {value : "KnowColonistDied", text : "Colonist died"},
    {value : "ColonistBanished", text : "Colonist banished"},
    {value : "ColonistBanishedToDie", text : "Colonist banished to death"},
    {value : "ColonistLeftUnburied", text : "Colonist left unburied"},
    {value : "NeedRoomSize", text : "Confined interior"},
    {value : "ClothedNudist", text : "Constraining clothes"},
    {value : "AteHumanlikeMeatAsIngredient", text : "Cooked cannibalism"},
    {value : "AteHumanlikeMeatAsIngredientCannibal", text : "Cooked cannibalism"},
    {value : "CrashedTogether", text : "Crashed together"},
    {value : "CreepyBreathing", text : "Creepy breathing"},
    {value : "EnvironmentDark", text : "Darkness"},
    {value : "DebugBad", text : "Debug bad thought"},
    {value : "DebugGood", text : "Debug good thought"},
    {value : "AteInImpressiveDiningRoom", text : "Decent dining room"},
    {value : "JoyActivityInImpressiveRecRoom", text : "Decent rec room"},
    {value : "DeepTalk", text : "Deep talk"},
    {value : "DefeatedHostileFactionLeader", text : "Defeated hostile leader {0}"},
    {value : "DefeatedHostileFactionLeaderOpinion", text : "Defeated hostile leader"},
    {value : "MoodOffsetDepressive", text : "Depressive"},
    {value : "Disfigured", text : "Disfigured"},
    {value : "SleepDisturbed", text : "Disturbed sleep"},
    {value : "DivorcedMe", text : "Divorced me"},
    {value : "DivorcedMeMood", text : "Divorced by {0}"},
    {value : "NeedRest", text : "Drowsy"},
    {value : "Drunk", text : "Drunk"},
    {value : "NeedOutdoors", text : "Entombed underground"},
    {value : "ExecutedPrisoner", text : "Executed prisoner"},
    {value : "FailedToRescueRelative", text : "Failed to rescue {0}"},
    {value : "FailedRomanceAttemptOnMe", text : "Failed to romance me"},
    {value : "ForcedMeToTakeDrugs", text : "Forced me to take drugs"},
    {value : "ForcedMeToTakeDrugsMood", text : "Forced to take drugs"},
    {value : "ForcedMeToTakeLuciferium", text : "Forced me to take luciferium"},
    {value : "ForcedMeToTakeLuciferiumMood", text : "Forced to take luciferium"},
    {value : "GoJuiceWithdrawal", text : "Go-juice withdrawal"},
    {value : "GotMarried", text : "Got married to {0}"},
    {value : "GotSomeLovin", text : "Got some lovin’"},
    {value : "Greedy", text : "Greedy for impressive bedroom"},
    {value : "FailedRomanceAttemptOnMeLowOpinionMood", text : "Had to rebuff {0}"},
    {value : "HappyNude", text : "Happily nude"},
    {value : "HardWorkerVsLazy", text : "Hard worker vs lazy"},
    {value : "HarmedMe", text : "Harmed me"},
    {value : "NeedBeauty", text : "Hideous environment"},
    {value : "GoJuiceHigh", text : "High on go-juice"},
    {value : "FlakeHigh", text : "High on flake"},
    {value : "YayoHigh", text : "High on yayo"},
    {value : "SmokeleafHigh", text : "High on smokeleaf"},
    {value : "HoneymoonPhase", text : "Honeymoon phase"},
    {value : "HumanLeatherApparelSad", text : "Human leather {0}"},
    {value : "HumanLeatherApparelHappy", text : "Human leather {0}"},
    {value : "NeedFood", text : "Hungry"},
    {value : "ButcheredHumanlikeCorpse", text : "I butchered humanlike"},
    {value : "IRejectedTheirProposal", text : "I rejected their proposal"},
    {value : "Incestuous", text : "Incestuous"},
    {value : "NewColonyOptimism", text : "Initial optimism"},
    {value : "NewColonyHope", text : "Initial hope"},
    {value : "KnowPrisonerDiedInnocent", text : "Innocent prisoner died"},
    {value : "Insulted", text : "Insulted"},
    {value : "InsultedMood", text : "Insulted"},
    {value : "Jealous", text : "Jealous of {0}'s bedroom"},
    {value : "Joywire", text : "Joywire"},
    {value : "KnowGuestExecuted", text : "Justified execution"},
    {value : "KnowColonistExecuted", text : "Justified execution of colonist"},
    {value : "KilledHumanlikeBloodlust", text : "Killed someone"},
    {value : "KilledMyFriend", text : "Killed my friend"},
    {value : "KilledMyRival", text : "Killed my rival"},
    {value : "KilledMyLover", text : "Killed my lover"},
    {value : "KilledMyFiance", text : "Killed my fiance"},
    {value : "KilledMySpouse", text : "Killed my spouse"},
    {value : "KilledMyFather", text : "Killed my father"},
    {value : "KilledMyMother", text : "Killed my mother"},
    {value : "KilledMySon", text : "Killed my son"},
    {value : "KilledMyDaughter", text : "Killed my daughter"},
    {value : "KilledMyBrother", text : "Killed my brother"},
    {value : "KilledMySister", text : "Killed my sister"},
    {value : "KilledMyKin", text : "Killed my kin"},
    {value : "KilledMyBondedAnimal", text : "Killed my bonded animal"},
    {value : "KilledColonist", text : "Killed colonist"},
    {value : "KilledColonyAnimal", text : "Killed colony animal"},
    {value : "KindWords", text : "Kind words"},
    {value : "KindWordsMood", text : "Kind words"},
    {value : "SoldMyLovedOne", text : "Loved one sold"},
    {value : "Man", text : "Man"},
    {value : "MasochistPain", text : "Masochist in minor pain"},
    {value : "Hungover", text : "Mild hangover"},
    {value : "Pain", text : "Minor pain"},
    {value : "DoingPassionateWork", text : "Minor passion for my work"},
    {value : "PawnWithGoodOpinionDied", text : "My friend {0} died"},
    {value : "PawnWithBadOpinionDied", text : "My rival {0} died"},
    {value : "MySonDied", text : "My son {0} died"},
    {value : "MyDaughterDied", text : "My daughter {0} died"},
    {value : "MyHusbandDied", text : "My husband {0} died"},
    {value : "MyWifeDied", text : "My wife {0} died"},
    {value : "MyFianceDied", text : "My fiance {0} died"},
    {value : "MyFianceeDied", text : "My fiancée {0} died"},
    {value : "MyLoverDied", text : "My lover {0} died"},
    {value : "MyBrotherDied", text : "My brother {0} died"},
    {value : "MySisterDied", text : "My sister {0} died"},
    {value : "MyGrandchildDied", text : "My grandchild {0} died"},
    {value : "MyFatherDied", text : "My father {0} died"},
    {value : "MyMotherDied", text : "My mother {0} died"},
    {value : "MyNieceDied", text : "My niece {0} died"},
    {value : "MyNephewDied", text : "My nephew {0} died"},
    {value : "MyHalfSiblingDied", text : "My half-sibling {0} died"},
    {value : "MyAuntDied", text : "My aunt {0} died"},
    {value : "MyUncleDied", text : "My uncle {0} died"},
    {value : "MyGrandparentDied", text : "My grandparent {0} died"},
    {value : "MyCousinDied", text : "My cousin {0} died"},
    {value : "MyKinDied", text : "My kin {0} died"},
    {value : "MyOrganHarvested", text : "My organ harvested"},
    {value : "RejectedMyProposalMood", text : "My proposal was rejected by {0}"},
    {value : "Naked", text : "Naked"},
    {value : "NightOwlDuringTheDay", text : "Night owl in daytime"},
    {value : "NightOwlDuringTheNight", text : "Night owl at night"},
    {value : "NotBondedAnimalMaster", text : "Not {0}'s master"},
    {value : "Nuzzled", text : "Nuzzled"},
    {value : "ObservedLayingCorpse", text : "Observed corpse"},
    {value : "ObservedLayingRottingCorpse", text : "Observed rotting corpse"},
    {value : "OpinionOfMyLover", text : "Opinion of my {0} {1}"},
    {value : "MoodOffsetOptimist", text : "Optimist"},
    {value : "MoodOffsetPessimist", text : "Pessimist"},
    {value : "Pretty", text : "Pretty"},
    {value : "PrisonerBanishedToDie", text : "Prisoner banished to death"},
    {value : "PsychicEmanatorSoothe", text : "Psychic emanator soothe"},
    {value : "PsychicDrone", text : "Psychic soothe"},
    {value : "PsychiteTeaHigh", text : "Psychite tea"},
    {value : "PsychiteWithdrawal", text : "Psychite withdrawal"},
    {value : "PyromaniacHappy", text : "Pyromaniac has incendiary weapon"},
    {value : "RapportBuilt", text : "Rapport built"},
    {value : "ApparelDamaged", text : "Ratty apparel"},
    {value : "AteHumanlikeMeatDirect", text : "Raw cannibalism"},
    {value : "AteHumanlikeMeatDirectCannibal", text : "Raw cannibalism"},
    {value : "RebuffedMyRomanceAttempt", text : "Rebuffed me"},
    {value : "RebuffedMyRomanceAttemptMood", text : "Rebuffed by {0}"},
    {value : "NeedJoy", text : "Recreation-starved"},
    {value : "RecruitedMe", text : "Recruited me"},
    {value : "RejectedMyProposal", text : "Rejected my proposal"},
    {value : "Rescued", text : "Rescued"},
    {value : "RescuedRelative", text : "Rescued {0}"},
    {value : "RescuedMe", text : "Rescued me"},
    {value : "MoodOffsetSanguine", text : "Sanguine"},
    {value : "SharedBed", text : "Sharing bed"},
    {value : "Sick", text : "Sick"},
    {value : "LowExpectations", text : "Sky-high expectations"},
    {value : "SleptOutside", text : "Slept outside"},
    {value : "SleptOnGround", text : "Slept on ground"},
    {value : "SleptInCold", text : "Slept in the cold"},
    {value : "SleptInHeat", text : "Slept in the heat"},
    {value : "Slighted", text : "Slighted"},
    {value : "SmokeleafWithdrawal", text : "Smokeleaf withdrawal"},
    {value : "SoakingWet", text : "Soaking wet"},
    {value : "SoldPrisoner", text : "Sold prisoner to slavery"},
    {value : "KnowGuestOrganHarvested", text : "Someone's organ harvested"},
    {value : "ArtifactMoodBoost", text : "Strange feeling"},
    {value : "EnvironmentHot", text : "Sweaty"},
    {value : "DeadMansApparel", text : "Tainted {0}"},
    {value : "TeetotalerVsChemicalInterest", text : "Teetotaler vs chemical interest"},
    {value : "TeetotalerVsAddict", text : "Teetotaler vs addict"},
    {value : "TranshumanistAppreciation", text : "Transhumanist appreciation"},
    {value : "ProsthophileNoProsthetic", text : "Transhumanist frustrated"},
    {value : "ProsthophileHappy", text : "Transhumanist pleased"},
    {value : "Ugly", text : "Ugly"},
    {value : "NeedComfort", text : "Uncomfortable"},
    {value : "WakeUpWithdrawal", text : "Wake-up withdrawal"},
    {value : "WantToSleepWithSpouseOrLover", text : "Want to sleep with {0}"},
    {value : "WasImprisoned", text : "Was imprisoned"},
    {value : "KnowButcheredHumanlikeCorpse", text : "We butchered humanlike"},
    {value : "WitnessedDeathAlly", text : "Witnessed ally's death"},
    {value : "WitnessedDeathNonAlly", text : "Witnessed outsider's death"},
    {value : "WitnessedDeathFamily", text : "Witnessed family member's death"},
    {value : "WitnessedDeathBloodlust", text : "Witnessed death with bloodlust"},
    {value : "Woman", text : "Woman"},
];
DataFile.Urgency = [
    {value : "None", text : "None"},
    {value : "Amble", text : "Amble"},
    {value : "Walk", text : "Walk"},
    {value : "Jog", text : "Jog"},
    {value : "Jog", text : "Jog"},
    {value : "Sprint", text : "Sprint"},
];
DataFile.ThingCategories = [
    {value : 'Undefined', text : 'Undefined'},
    {value : 'Nothing', text : 'Nothing'},
    {value : 'Everything', text : 'Everything'},
    {value : 'HaulableEver', text : 'Ever haulable'},
    {value : 'HaulableAlways', text : 'Always haulable'},
    {value : 'FoodSource', text : 'Food source'},
    {value : 'FoodSourceNotPlantOrTree', text : 'Food source not plant or tree'},
    {value : 'Corpse', text : 'Corpse'},
    {value : 'Blueprint', text : 'Blueprint'},
    {value : 'BuildingArtificial', text : 'Artificial building'},
    {value : 'BuildingFrame', text : 'Building frame'},
    {value : 'Pawn', text : 'Pawn'},
    {value : 'PotentialBillGiver', text : 'Potential bill giver'},
    {value : 'Medicine', text : 'Medicine'},
    {value : 'Filth', text : 'Filth'},
    {value : 'AttackTarget', text : 'Attackable target'},
    {value : 'Weapon', text : 'Weapon'},
    {value : 'Refuelable', text : 'Refuelable'},
    {value : 'HaulableEverOrMinifiable', text : 'Ever haulable or minifiable'},
    {value : 'Drug', text : 'Drug'},
    {value : 'Shell', text : 'Shell'},
    {value : 'HarvestablePlant', text : 'Harvestable plant'},
    {value : 'Fire', text : 'Fire'},
    {value : 'Plant', text : 'Plant'},
    {value : 'Construction', text : 'Construction'},
    {value : 'HasGUIOverlay', text : 'Has GUI overlay'},
    {value : 'Apparel', text : 'Apparel'},
    {value : 'MinifiedThing', text : 'Minified Thing'},
    {value : 'Grave', text : 'Grave'},
    {value : 'Art', text : 'Art'},
    {value : 'ThingHolder', text : 'Thing Holder'},
    {value : 'ActiveDropPod', text : 'Active drop pod'},
    {value : 'Transporter', text : 'Transporter'},
    {value : 'LongRangeMineralScanner', text : 'Long range mineral scanner'},
    {value : 'AffectsSky', text : 'Affects sky'},
    {value : 'PsychicDroneEmanator', text : 'Psychic drone emanator'},
    {value : 'WindSource', text : 'Wind source'},
    {value : 'AlwaysFlee', text : 'Always flee'},
    {value : 'ResearchBench', text : 'Research bench'},
    {value : 'Facility', text : 'Facility'},
    {value : 'AffectedByFacilities', text : 'Affected by facilities'},
    {value : 'CreatesInfestations', text : 'Creates infestations'},
];
DataFile.Plants = [
    {value : "Agarilux", text : "Agarilux"},
    {value : "Plant_Agave", text : "Agave"},
    {value : "Plant_Alocasia", text : "Alocasia"},
    {value : "Plant_Ambrosia", text : "Ambrosia"},
    {value : "Plant_Astragalus", text : "Astragalus"},
    {value : "Plant_Berry", text : "Berry"},
    {value : "Plant_Brambles", text : "Brambles"},
    {value : "Bryolux", text : "Bryolux"},
    {value : "BurnedTree", text : "Burned tree"},
    {value : "Plant_Bush", text : "Bush"},
    {value : "Plant_Chokevine", text : "Chokevine"},
    {value : "Plant_Clivia", text : "Clivia"},
    {value : "Plant_Corn", text : "Corn"},
    {value : "Plant_Cotton", text : "Cotton"},
    {value : "Plant_Dandelion", text : "Dandelion"},
    {value : "Plant_Daylily", text : "Daylily"},
    {value : "Plant_Devilstrand", text : "Devilstrand"},
    {value : "Glowstool", text : "Glowstool"},
    {value : "Plant_Grass", text : "Grass"},
    {value : "Plant_Haygrass", text : "Haygrass"},
    {value : "Plant_Healroot", text : "Healroot"},
    {value : "Plant_HealrootWild", text : "Healroot Wild"},
    {value : "Plant_Hops", text : "Hops"},
    {value : "Plant_Moss", text : "Moss"},
    {value : "Plant_PincushionCactus", text : "Pincushion Cactus"},
    {value : "Plant_Potato", text : "Potato"},
    {value : "Plant_Psychoid", text : "Psychoid"},
    {value : "Plant_Rafflesia", text : "Rafflesia"},
    {value : "Plant_Rice", text : "Rice"},
    {value : "Plant_Rose", text : "Rose"},
    {value : "Plant_SaguaroCactus", text : "Saguaro Cactus"},
    {value : "Plant_ShrubLow", text : "Shrub Low"},
    {value : "Plant_Smokeleaf", text : "Smokeleaf"},
    {value : "Plant_Strawberry", text : "Strawberry"},
    {value : "Plant_TallGrass", text : "Tall Grass"},
    {value : "Plant_TreeBamboo", text : "Tree Bamboo"},
    {value : "Plant_TreeBirch", text : "Tree Birch"},
    {value : "Plant_TreeCecropia", text : "Tree Cecropia"},
    {value : "Plant_TreeCypress", text : "Tree Cypress"},
    {value : "Plant_TreeDrago", text : "Tree Drago"},
    {value : "Plant_TreeMaple", text : "Tree Maple"},
    {value : "Plant_TreeOak", text : "Tree Oak"},
    {value : "Plant_TreePalm", text : "Tree Palm"},
    {value : "Plant_TreePine", text : "Tree Pine"},
    {value : "Plant_TreePoplar", text : "Tree Poplar"},
    {value : "Plant_TreeTeak", text : "Tree Teak"},
    {value : "Plant_TreeWillow", text : "Tree Willow"},
    {value : "Plant_TreeCocoa", text : "TreeCocoa"},
];
DataFile.AnimalTypes = [
    {value : "Alpaca", text : "Alpaca"},
    {value : "Alphabeaver", text : "Alphabeaver"},
    {value : "Wolf_Arctic", text : "Arctic Wolf"},
    {value : "Fox_Arctic", text : "Arctic Fox"},
    {value : "Boomalope", text : "Boomalope"},
    {value : "Boomrat", text : "Boomrat"},
    {value : "Capybara", text : "Capybara"},
    {value : "Caribou", text : "Caribou"},
    {value : "Cassowary", text : "Cassowary"},
    {value : "Cat", text : "Cat"},
    {value : "Chicken", text : "Chicken"},
    {value : "Chinchilla", text : "Chinchilla"},
    {value : "Cobra", text : "Cobra"},
    {value : "Cougar", text : "Cougar"},
    {value : "Cow", text : "Cow"},
    {value : "Deer", text : "Deer"},
    {value : "Dromedary", text : "Dromedary"},
    {value : "Elephant", text : "Elephant"},
    {value : "Elk", text : "Elk"},
    {value : "Emu", text : "Emu"},
    {value : "Fox_Fennec", text : "Fennec Fox"},
    {value : "Gazelle", text : "Gazelle"},
    {value : "Bear_Grizzly", text : "Grizzly Bear"},
    {value : "Hare", text : "Hare"},
    {value : "Husky", text : "Husky"},
    {value : "Ibex", text : "Ibex"},
    {value : "Iguana", text : "Iguana"},
    {value : "LabradorRetriever", text : "Labrador Retriever"},
    {value : "Lynx", text : "Lynx"},
    {value : "Megascarab", text : "Megascarab"},
    {value : "Megasloth", text : "Megasloth"},
    {value : "Megaspider", text : "Megaspider"},
    {value : "Monkey", text : "Monkey"},
    {value : "Muffalo", text : "Muffalo"},
    {value : "Ostrich", text : "Ostrich"},
    {value : "Panther", text : "Panther"},
    {value : "Pig", text : "Pig"},
    {value : "Bear_Polar", text : "Polar Bear"},
    {value : "Raccoon", text : "Raccoon"},
    {value : "Rat", text : "Rat"},
    {value : "Fox_Red", text : "Red Fox"},
    {value : "Rhinoceros", text : "Rhinoceros"},
    {value : "Snowhare", text : "Snowhare"},
    {value : "Spelopede", text : "Spelopede"},
    {value : "Squirrel", text : "Squirrel"},
    {value : "Thrumbo", text : "Thrumbo"},
    {value : "Wolf_Timber", text : "Timber Wolf"},
    {value : "Tortoise", text : "Tortoise"},
    {value : "Turkey", text : "Turkey"},
    {value : "Warg", text : "Warg"},
    {value : "WildBoar", text : "Wild Boar"},
    {value : "YorkshireTerrier", text : "Yorkshire Terrier"},
];
DataFile.PawnTraits = [
    {value : "Nudist|0", text : "Nudist"},
    {value : "Bloodlust|0", text : "Bloodlust"},
    {value : "Kind|0", text : "Kind"},
    {value : "Psychopath|0", text : "Psychopath"},
    {value : "Cannibal|0", text : "Cannibal"},
    {value : "Abrasive|0", text : "Abrasive"},
    {value : "TooSmart|0", text : "Too smart"},
    {value : "Brawler|0", text : "Brawler"},
    {value : "Masochist|0", text : "Masochist"},
    {value : "NightOwl|0", text : "Night owl"},
    {value : "Greedy|0", text : "Greedy"},
    {value : "Jealous|0", text : "Jealous"},
    {value : "Ascetic|0", text : "Ascetic"},
    {value : "Gay|0", text : "Gay"},
    {value : "AnnoyingVoice|0", text : "Annoying voice"},
    {value : "CreepyBreathing|0", text : "Creepy breathing"},
    {value : "Pyromaniac|0", text : "Pyromaniac"},
    {value : "Wimp|0", text : "Wimp"},
    {value : "Nimble|0", text : "Nimble"},
    {value : "FastLearner|0", text : "Fast learner"},
    {value : "Undergrounder|0", text : "Undergrounder"},
    {value : "Transhumanist|0", text : "Transhumanist"},
    {value : "BodyPurist|0", text : "Body purist"},
    {value : "DislikesMen|0", text : "Misandrist"},
    {value : "DislikesWomen|0", text : "Misogynist"},
    {value : "GreatMemory|0", text : "Great memory"},
    {value : "Tough|0", text : "Tough"},
    {value : "Gourmand|0", text : "Gourmand"},
    {value : "QuickSleeper|0", text : "Quick sleeper"},
    {value : "SpeedOffset|-1", text : "Slowpoke"},
    {value : "SpeedOffset|1", text : "Fast walker"},
    {value : "SpeedOffset|2", text : "Jogger"},
    {value : "DrugDesire|2", text : "Chemical fascination"},
    {value : "DrugDesire|1", text : "Chemical interest"},
    {value : "DrugDesire|-1", text : "Teetotaler"},
    {value : "NaturalMood|2", text : "Sanguine"},
    {value : "NaturalMood|1", text : "Optimist"},
    {value : "NaturalMood|-1", text : "Pessimist"},
    {value : "NaturalMood|-2", text : "Depressive"},
    {value : "Nerves|2", text : "Iron-willed"},
    {value : "Nerves|1", text : "Steadfast"},
    {value : "Nerves|-1", text : "Nervous"},
    {value : "Nerves|-2", text : "Volatile"},
    {value : "Neurotic|1", text : "Neurotic"},
    {value : "Neurotic|2", text : "Very neurotic"},
    {value : "Industriousness|2", text : "Industrious"},
    {value : "Industriousness|1", text : "Hard worker"},
    {value : "Industriousness|-1", text : "Lazy"},
    {value : "Industriousness|-2", text : "Slothful"},
    {value : "PsychicSensitivity|2", text : "Psychically hypersensitive"},
    {value : "PsychicSensitivity|1", text : "Psychically sensitive"},
    {value : "PsychicSensitivity|-1", text : "Psychically dull"},
    {value : "PsychicSensitivity|-2", text : "Psychically deaf"},
    {value : "ShootingAccuracy|1", text : "Careful shooter"},
    {value : "ShootingAccuracy|-1", text : "Trigger-happy"},
    {value : "Beauty|2", text : "Beautiful"},
    {value : "Beauty|1", text : "Pretty"},
    {value : "Beauty|-1", text : "Ugly"},
    {value : "Beauty|-2", text : "Staggeringly ugly"},
    {value : "Immunity|1", text : "Super-immune"},
    {value : "Immunity|-1", text : "Sickly"},
];
DataFile.HairTypes = [
    {value : "Afro", text : "Afro"},
    {value : "Bob", text : "Bob"},
    {value : "Burgundy", text : "Burgundy"},
    {value : "Flowy", text : "Flowy"},
    {value : "Long", text : "Long"},
    {value : "Mohawk", text : "Mohawk"},
    {value : "Mop", text : "Mop"},
    {value : "Pigtails", text : "Pigtails"},
    {value : "Shaved", text : "Shaved"},
    {value : "Spikes", text : "Spikes"},
    {value : "Tuft", text : "Tuft"},
    {value : "Wavy", text : "Wavy"},
    {value : "BraidedKnot", text : "Braided knot"},
    {value : "Topdog", text : "Topdog"},
    {value : "Senorita", text : "Senorita"},
    {value : "ScorpionTail", text : "Scorpion tail"},
    {value : "BriefPonytail", text : "Brief ponytail"},
    {value : "Troubadour", text : "Troubadour"},
    {value : "Messy", text : "Messy"},
    {value : "Princess", text : "Princess"},
    {value : "Firestarter", text : "Firestarter"},
    {value : "GreasySwoop", text : "Greasy swoop"},
    {value : "Curly", text : "Curly"},
    {value : "Scatman", text : "Scatman"},
];
DataFile.BodyTypes = [
    {value : "Male", text : "Male"},
    {value : "Female", text : "Female"},
    {value : "Thin", text : "Thin"},
    {value : "Hulk", text : "Hulk"},
    {value : "Fat", text : "Fat"},
];
DataFile.Items = [
    {value : "ComponentSpacer", text : "Advanced component"},
    {value : "Apparel_AdvancedHelmet", text : "Advanced helmet"},
    {value : "RawAgave", text : "Agave fruit"},
    {value : "AIPersonaCore", text : "AI persona core"},
    {value : "WoolAlpaca", text : "Alpaca wool"},
    {value : "Meat_Alpaca", text : "Alpaca meat"},
    {value : "Corpse_Alpaca", text : "Alpaca corpse"},
    {value : "Meat_Alphabeaver", text : "Alphabeaver meat"},
    {value : "Corpse_Alphabeaver", text : "Alphabeaver corpse"},
    {value : "Ambrosia", text : "Ambrosia"},
    {value : "AnimalSleepingBox", text : "Animal sleeping box"},
    {value : "AnimalBed", text : "Animal bed"},
    {value : "Shell_AntigrainWarhead", text : "Antigrain warhead"},
    {value : "ArchotechEye", text : "Archotech eye"},
    {value : "ArchotechArm", text : "Archotech arm"},
    {value : "ArchotechLeg", text : "Archotech leg"},
    {value : "Corpse_Wolf_Arctic", text : "Arctic wolf corpse"},
    {value : "Corpse_Fox_Arctic", text : "Arctic fox corpse"},
    {value : "Armchair", text : "Armchair"},
    {value : "Gun_AssaultRifle", text : "Assault rifle"},
    {value : "Gun_AutocannonTurret", text : "Autocannon"},
    {value : "Gun_Autopistol", text : "Autopistol"},
    {value : "Battery", text : "Battery"},
    {value : "Meat_Bear_Grizzly", text : "Bear meat"},
    {value : "Leather_Bear", text : "Bearskin"},
    {value : "Bed", text : "Bed"},
    {value : "Bedroll", text : "Bedroll"},
    {value : "Meat_Cow", text : "Beef"},
    {value : "Beer", text : "Beer"},
    {value : "RawBerries", text : "Berries"},
    {value : "BilliardsTable", text : "Billiards table"},
    {value : "BionicEye", text : "Bionic eye"},
    {value : "BionicArm", text : "Bionic arm"},
    {value : "BionicLeg", text : "Bionic leg"},
    {value : "BionicSpine", text : "Bionic spine"},
    {value : "BionicHeart", text : "Bionic heart"},
    {value : "BionicStomach", text : "Bionic stomach"},
    {value : "BionicEar", text : "Bionic ear"},
    {value : "Meat_Cassowary", text : "Bird meat"},
    {value : "Leather_Bird", text : "Birdskin"},
    {value : "Leather_Bluefur", text : "Bluefur"},
    {value : "Gun_BoltActionRifle", text : "Bolt-action rifle"},
    {value : "Meat_Boomalope", text : "Boomalope meat"},
    {value : "Corpse_Boomalope", text : "Boomalope corpse"},
    {value : "Meat_Boomrat", text : "Boomrat meat"},
    {value : "Corpse_Boomrat", text : "Boomrat corpse"},
    {value : "Apparel_BowlerHat", text : "Bowler hat"},
    {value : "Brewery", text : "Brewery"},
    {value : "TableButcher", text : "Butcher table"},
    {value : "Apparel_CollarShirt", text : "Button-down shirt"},
    {value : "WoolCamel", text : "Camelhair"},
    {value : "Leather_Camel", text : "Camelhide"},
    {value : "Meat_Capybara", text : "Capybara meat"},
    {value : "Corpse_Capybara", text : "Capybara corpse"},
    {value : "Meat_Caribou", text : "Caribou meat"},
    {value : "Corpse_Caribou", text : "Caribou corpse"},
    {value : "EggCassowaryFertilized", text : "Cassowary egg (fert.)"},
    {value : "Corpse_Cassowary", text : "Cassowary corpse"},
    {value : "Meat_Cat", text : "Cat meat"},
    {value : "Corpse_Cat", text : "Cat corpse"},
    {value : "Corpse_Mech_Centipede", text : "Centipede corpse"},
    {value : "Gun_ChainShotgun", text : "Chain shotgun"},
    {value : "Gun_ChargeRifle", text : "Charge rifle"},
    {value : "Gun_ChargeLance", text : "Charge lance"},
    {value : "Chemfuel", text : "Chemfuel"},
    {value : "ChessTable", text : "Chess table"},
    {value : "EggChickenUnfertilized", text : "Chicken egg (unfert.)"},
    {value : "EggChickenFertilized", text : "Chicken egg (fert.)"},
    {value : "Meat_Chicken", text : "Chicken meat"},
    {value : "Corpse_Chicken", text : "Chicken corpse"},
    {value : "Leather_Chinchilla", text : "Chinchilla fur"},
    {value : "Meat_Chinchilla", text : "Chinchilla meat"},
    {value : "Corpse_Chinchilla", text : "Chinchilla corpse"},
    {value : "Chocolate", text : "Chocolate"},
    {value : "Cloth", text : "Cloth"},
    {value : "MeleeWeapon_Club", text : "Club"},
    {value : "EggCobraFertilized", text : "Cobra egg (fert.)"},
    {value : "Corpse_Cobra", text : "Cobra corpse"},
    {value : "Meat_Cobra", text : "Cobraflesh"},
    {value : "CochlearImplant", text : "Cochlear implant"},
    {value : "ComponentIndustrial", text : "Component"},
    {value : "RawCorn", text : "Corn"},
    {value : "Meat_Cougar", text : "Cougar meat"},
    {value : "Corpse_Cougar", text : "Cougar corpse"},
    {value : "Corpse_Cow", text : "Cow corpse"},
    {value : "Apparel_CowboyHat", text : "Cowboy hat"},
    {value : "DeepDrill", text : "Deep drill"},
    {value : "Corpse_Deer", text : "Deer corpse"},
    {value : "DevilstrandCloth", text : "Devilstrand"},
    {value : "DiningChair", text : "Dining chair"},
    {value : "Leather_Dog", text : "Dog leather"},
    {value : "Gun_DoomsdayRocket", text : "Doomsday rocket launcher"},
    {value : "DoubleBed", text : "Double bed"},
    {value : "BedrollDouble", text : "Double bedroll"},
    {value : "Dresser", text : "Dresser"},
    {value : "Meat_Dromedary", text : "Dromedary meat"},
    {value : "Corpse_Dromedary", text : "Dromedary corpse"},
    {value : "DrugLab", text : "Drug lab"},
    {value : "Apparel_Duster", text : "Duster"},
    {value : "ElectricTailoringBench", text : "Electric tailor bench"},
    {value : "ElectricSmithy", text : "Electric smithy"},
    {value : "ElectricStove", text : "Electric stove"},
    {value : "ElectricSmelter", text : "Electric smelter"},
    {value : "ElephantTusk", text : "Elephant tusk"},
    {value : "Leather_Elephant", text : "Elephant leather"},
    {value : "Meat_Elephant", text : "Elephant meat"},
    {value : "Corpse_Elephant", text : "Elephant corpse"},
    {value : "Meat_Elk", text : "Elk meat"},
    {value : "Corpse_Elk", text : "Elk corpse"},
    {value : "Shell_EMP", text : "EMP shell"},
    {value : "Weapon_GrenadeEMP", text : "EMP grenades"},
    {value : "EggEmuFertilized", text : "Emu egg (fert.)"},
    {value : "Corpse_Emu", text : "Emu corpse"},
    {value : "EndTable", text : "End table"},
    {value : "Corpse_Fox_Fennec", text : "Fennec fox corpse"},
    {value : "FermentingBarrel", text : "Fermenting barrel"},
    {value : "MealFine", text : "Fine meal"},
    {value : "FirefoamPopper", text : "Firefoam popper"},
    {value : "Shell_Firefoam", text : "Firefoam shell"},
    {value : "Apparel_FlakVest", text : "Flak vest"},
    {value : "Apparel_FlakPants", text : "Flak pants"},
    {value : "Apparel_FlakJacket", text : "Flak jacket"},
    {value : "Flake", text : "Flake"},
    {value : "FlatscreenTelevision", text : "Flatscreen television"},
    {value : "Leather_Fox", text : "Foxfur"},
    {value : "Meat_Fox_Fennec", text : "Foxmeat"},
    {value : "Weapon_GrenadeFrag", text : "Frag grenades"},
    {value : "FueledSmithy", text : "Fueled smithy"},
    {value : "FueledStove", text : "Fueled stove"},
    {value : "GameOfUrBoard", text : "Game-of-Ur board"},
    {value : "Meat_Gazelle", text : "Gazelle meat"},
    {value : "Corpse_Gazelle", text : "Gazelle corpse"},
    {value : "MeleeWeapon_Gladius", text : "Gladius"},
    {value : "MedicineUltratech", text : "Glitterworld medicine"},
    {value : "GlowPod", text : "Glow pod"},
    {value : "GoJuice", text : "Go-juice"},
    {value : "Gold", text : "Gold"},
    {value : "SculptureGrand", text : "Grand sculpture"},
    {value : "ChunkGranite", text : "Granite chunk"},
    {value : "BlocksGranite", text : "Granite blocks"},
    {value : "Bow_Great", text : "Greatbow"},
    {value : "Corpse_Bear_Grizzly", text : "Grizzly bear corpse"},
    {value : "HandTailoringBench", text : "Hand tailor bench"},
    {value : "Meat_Hare", text : "Hare meat"},
    {value : "Corpse_Hare", text : "Hare corpse"},
    {value : "Hay", text : "Hay"},
    {value : "MechSerumHealer", text : "Healer mech serum"},
    {value : "Heart", text : "Heart"},
    {value : "Heater", text : "Heater"},
    {value : "Leather_Heavy", text : "Heavy fur"},
    {value : "Gun_HeavySMG", text : "Heavy SMG"},
    {value : "Gun_ChargeBlasterHeavy", text : "Heavy charge blaster"},
    {value : "MedicineHerbal", text : "Herbal medicine"},
    {value : "Shell_HighExplosive", text : "High-explosive shell"},
    {value : "HoopstoneRing", text : "Hoopstone ring"},
    {value : "RawHops", text : "Hops"},
    {value : "HorseshoesPin", text : "Horseshoes pin"},
    {value : "HospitalBed", text : "Hospital bed"},
    {value : "Leather_Human", text : "Human leather"},
    {value : "Meat_Human", text : "Human meat"},
    {value : "Corpse_Human", text : "Human corpse"},
    {value : "Meat_Husky", text : "Husky meat"},
    {value : "Corpse_Husky", text : "Husky corpse"},
    {value : "Hyperweave", text : "Hyperweave"},
    {value : "Meat_Ibex", text : "Ibex meat"},
    {value : "Corpse_Ibex", text : "Ibex corpse"},
    {value : "TrapIED_HighExplosive", text : "IED trap"},
    {value : "TrapIED_Incendiary", text : "IED incendiary trap"},
    {value : "TrapIED_EMP", text : "IED EMP trap"},
    {value : "TrapIED_Firefoam", text : "IED firefoam trap"},
    {value : "TrapIED_AntigrainWarhead", text : "IED antigrain warhead trap"},
    {value : "EggIguanaFertilized", text : "Iguana egg (fert.)"},
    {value : "Meat_Iguana", text : "Iguana meat"},
    {value : "Corpse_Iguana", text : "Iguana corpse"},
    {value : "MeleeWeapon_Ikwa", text : "Ikwa"},
    {value : "Shell_Incendiary", text : "Incendiary shell"},
    {value : "Gun_IncendiaryLauncher", text : "Incendiary launcher"},
    {value : "Gun_InfernoCannon", text : "Inferno cannon"},
    {value : "InfiniteChemreactor", text : "Infinite chemreactor"},
    {value : "InsectJelly", text : "Insect jelly"},
    {value : "Meat_Megaspider", text : "Insect meat"},
    {value : "Apparel_Jacket", text : "Jacket"},
    {value : "Jade", text : "Jade"},
    {value : "Joywire", text : "Joywire"},
    {value : "Kibble", text : "Kibble"},
    {value : "Kidney", text : "Kidney"},
    {value : "MeleeWeapon_Knife", text : "Knife"},
    {value : "Meat_LabradorRetriever", text : "Labrador retriever meat"},
    {value : "Corpse_LabradorRetriever", text : "Labrador retriever corpse"},
    {value : "Corpse_Mech_Lancer", text : "Lancer corpse"},
    {value : "SculptureLarge", text : "Large sculpture"},
    {value : "MealLavish", text : "Lavish meal"},
    {value : "Leather_Light", text : "Lightleather"},
    {value : "ChunkLimestone", text : "Limestone chunk"},
    {value : "BlocksLimestone", text : "Limestone blocks"},
    {value : "Liver", text : "Liver"},
    {value : "Leather_Lizard", text : "Lizardskin"},
    {value : "Gun_LMG", text : "LMG"},
    {value : "MeleeWeapon_LongSword", text : "Longsword"},
    {value : "Luciferium", text : "Luciferium"},
    {value : "Lung", text : "Lung"},
    {value : "Meat_Lynx", text : "Lynx meat"},
    {value : "Corpse_Lynx", text : "Lynx corpse"},
    {value : "MeleeWeapon_Mace", text : "Mace"},
    {value : "Gun_MachinePistol", text : "Machine pistol"},
    {value : "TableMachining", text : "Machining table"},
    {value : "ChunkMarble", text : "Marble chunk"},
    {value : "BlocksMarble", text : "Marble blocks"},
    {value : "Apparel_PowerArmorHelmet", text : "Marine helmet"},
    {value : "Apparel_PowerArmor", text : "Marine armor"},
    {value : "MedicineIndustrial", text : "Medicine"},
    {value : "Corpse_Megascarab", text : "Megascarab corpse"},
    {value : "MegascreenTelevision", text : "Megascreen television"},
    {value : "WoolMegasloth", text : "Megasloth wool"},
    {value : "Meat_Megasloth", text : "Megasloth meat"},
    {value : "Corpse_Megasloth", text : "Megasloth corpse"},
    {value : "Corpse_Megaspider", text : "Megaspider corpse"},
    {value : "Milk", text : "Milk"},
    {value : "Turret_MiniTurret", text : "Mini-turret"},
    {value : "Gun_MiniTurret", text : "Mini-turret gun"},
    {value : "MinifiedThing", text : "Minified thing"},
    {value : "Gun_Minigun", text : "Minigun"},
    {value : "Weapon_GrenadeMolotov", text : "Molotov cocktails"},
    {value : "Meat_Monkey", text : "Monkey meat"},
    {value : "Corpse_Monkey", text : "Monkey corpse"},
    {value : "Turret_Mortar", text : "Mortar"},
    {value : "WoolMuffalo", text : "Muffalo wool"},
    {value : "Meat_Muffalo", text : "Muffalo meat"},
    {value : "Corpse_Muffalo", text : "Muffalo corpse"},
    {value : "MultiAnalyzer", text : "Multi-analyzer"},
    {value : "MechSerumNeurotrainer", text : "Neurotrainer mech serum"},
    {value : "Neutroamine", text : "Neutroamine"},
    {value : "MealNutrientPaste", text : "Nutrient paste meal"},
    {value : "OrbitalTradeBeacon", text : "Orbital trade beacon"},
    {value : "OrbitalTargeterBombardment", text : "Orbital bombardment targeter"},
    {value : "OrbitalTargeterPowerBeam", text : "Orbital power beam targeter"},
    {value : "EggOstrichFertilized", text : "Ostrich egg (fert.)"},
    {value : "Corpse_Ostrich", text : "Ostrich corpse"},
    {value : "MealSurvivalPack", text : "Packaged survival meal"},
    {value : "Painstopper", text : "Painstopper"},
    {value : "Meat_Panther", text : "Panther meat"},
    {value : "Corpse_Panther", text : "Panther corpse"},
    {value : "Leather_Panthera", text : "Panthera fur"},
    {value : "Apparel_Pants", text : "Pants"},
    {value : "Apparel_Parka", text : "Parka"},
    {value : "Leather_Patch", text : "Patchleather"},
    {value : "Pemmican", text : "Pemmican"},
    {value : "Penoxycyline", text : "Penoxycyline"},
    {value : "Corpse_Pig", text : "Pig corpse"},
    {value : "Leather_Pig", text : "Pigskin"},
    {value : "Pila", text : "Pila"},
    {value : "Leather_Plain", text : "Plainleather"},
    {value : "PlantPot", text : "Plant pot"},
    {value : "Plasteel", text : "Plasteel"},
    {value : "Apparel_PlateArmor", text : "Plate armor"},
    {value : "PokerTable", text : "Poker table"},
    {value : "Corpse_Bear_Polar", text : "Polar bear corpse"},
    {value : "Meat_Pig", text : "Pork"},
    {value : "RawPotatoes", text : "Potatoes"},
    {value : "PowerClaw", text : "Power claw"},
    {value : "SimpleProstheticLeg", text : "Prosthetic leg"},
    {value : "SimpleProstheticArm", text : "Prosthetic arm"},
    {value : "SimpleProstheticHeart", text : "Prosthetic heart"},
    {value : "PsychicEmanator", text : "Psychic emanator"},
    {value : "PsychicInsanityLance", text : "Psychic insanity lance"},
    {value : "PsychicShockLance", text : "Psychic shock lance"},
    {value : "PsychicAnimalPulser", text : "Psychic animal pulser"},
    {value : "PsychicSoothePulser", text : "Psychic soothe pulser"},
    {value : "Apparel_PsychicFoilHelmet", text : "Psychic foil helmet"},
    {value : "PsychiteTea", text : "Psychite tea"},
    {value : "PsychoidLeaves", text : "Psychoid leaves"},
    {value : "Gun_PumpShotgun", text : "Pump shotgun"},
    {value : "Meat_Raccoon", text : "Raccoon meat"},
    {value : "Corpse_Raccoon", text : "Raccoon corpse"},
    {value : "Meat_Rat", text : "Rat meat"},
    {value : "Corpse_Rat", text : "Rat corpse"},
    {value : "RawFungus", text : "Raw fungus"},
    {value : "Bow_Recurve", text : "Recurve bow"},
    {value : "Corpse_Fox_Red", text : "Red fox corpse"},
    {value : "MechSerumResurrector", text : "Resurrector mech serum"},
    {value : "Gun_Revolver", text : "Revolver"},
    {value : "Leather_Rhinoceros", text : "Rhinoceros leather"},
    {value : "Meat_Rhinoceros", text : "Rhinoceros meat"},
    {value : "Corpse_Rhinoceros", text : "Rhinoceros corpse"},
    {value : "RawRice", text : "Rice"},
    {value : "RoyalBed", text : "Royal bed"},
    {value : "ChunkSandstone", text : "Sandstone chunk"},
    {value : "BlocksSandstone", text : "Sandstone blocks"},
    {value : "TableSculpting", text : "Sculptor's table"},
    {value : "Corpse_Mech_Scyther", text : "Scyther corpse"},
    {value : "Shelf", text : "Shelf"},
    {value : "Apparel_ShieldBelt", text : "Shield belt"},
    {value : "Bow_Short", text : "Short bow"},
    {value : "Silver", text : "Silver"},
    {value : "SimpleResearchBench", text : "Simple research bench"},
    {value : "MealSimple", text : "Simple meal"},
    {value : "Apparel_SimpleHelmet", text : "Simple helmet"},
    {value : "ChunkSlate", text : "Slate chunk"},
    {value : "BlocksSlate", text : "Slate blocks"},
    {value : "SculptureSmall", text : "Small sculpture"},
    {value : "SmokeleafJoint", text : "Smokeleaf joint"},
    {value : "SmokeleafLeaves", text : "Smokeleaf leaves"},
    {value : "Apparel_SmokepopBelt", text : "Smokepop belt"},
    {value : "Gun_SniperRifle", text : "Sniper rifle"},
    {value : "Corpse_Snowhare", text : "Snowhare corpse"},
    {value : "MeleeWeapon_Spear", text : "Spear"},
    {value : "Corpse_Spelopede", text : "Spelopede corpse"},
    {value : "TrapSpike", text : "Spike trap"},
    {value : "Meat_Squirrel", text : "Squirrel meat"},
    {value : "Corpse_Squirrel", text : "Squirrel corpse"},
    {value : "StandingLamp", text : "Standing lamp"},
    {value : "StandingLamp_Red", text : "Standing lamp (red)"},
    {value : "StandingLamp_Green", text : "Standing lamp (green)"},
    {value : "StandingLamp_Blue", text : "Standing lamp (blue)"},
    {value : "Steel", text : "Steel"},
    {value : "ChunkSlagSteel", text : "Steel slag chunk"},
    {value : "TableStonecutter", text : "Stonecutter's table"},
    {value : "Stool", text : "Stool"},
    {value : "SunLamp", text : "Sun lamp"},
    {value : "Synthread", text : "Synthread"},
    {value : "Apparel_BasicShirt", text : "T-shirt"},
    {value : "Table1x2c", text : "Table (1x2)"},
    {value : "Table2x2c", text : "Table (2x2)"},
    {value : "Table2x4c", text : "Table (2x4)"},
    {value : "Table3x3c", text : "Table (3x3)"},
    {value : "TechprofSubpersonaCore", text : "Techprof subpersona core"},
    {value : "Telescope", text : "Telescope"},
    {value : "ThrumboHorn", text : "Thrumbo horn"},
    {value : "Meat_Thrumbo", text : "Thrumbo meat"},
    {value : "Corpse_Thrumbo", text : "Thrumbo corpse"},
    {value : "Leather_Thrumbo", text : "Thrumbofur"},
    {value : "Corpse_Wolf_Timber", text : "Timber wolf corpse"},
    {value : "ToolCabinet", text : "Tool cabinet"},
    {value : "TornadoGenerator", text : "Tornado generator"},
    {value : "EggTortoiseFertilized", text : "Tortoise egg (fert.)"},
    {value : "Meat_Tortoise", text : "Tortoise meat"},
    {value : "Corpse_Tortoise", text : "Tortoise corpse"},
    {value : "Apparel_TribalHeaddress", text : "Tribal headdress"},
    {value : "Apparel_TribalA", text : "Tribalwear"},
    {value : "Gun_TripleRocket", text : "Triple rocket launcher"},
    {value : "TubeTelevision", text : "Tube television"},
    {value : "Apparel_Tuque", text : "Tuque"},
    {value : "EggTurkeyFertilized", text : "Turkey egg (fert.)"},
    {value : "Meat_Turkey", text : "Turkey meat"},
    {value : "Corpse_Turkey", text : "Turkey corpse"},
    {value : "UnfinishedSculpture", text : "Unfinished sculpture"},
    {value : "UnfinishedGun", text : "Unfinished gun"},
    {value : "UnfinishedWeapon", text : "Unfinished weapon"},
    {value : "UnfinishedArmor", text : "Unfinished armor"},
    {value : "UnfinishedTechArmor", text : "Unfinished armor"},
    {value : "UnfinishedMetallicTechArmor", text : "Unfinished armor"},
    {value : "UnfinishedApparel", text : "Unfinished apparel"},
    {value : "UnfinishedBelt", text : "Unfinished belt"},
    {value : "UnfinishedComponent", text : "Unfinished component"},
    {value : "Uranium", text : "Uranium"},
    {value : "Gun_TurretSniper", text : "Uranium slug cannon"},
    {value : "VanometricPowerCell", text : "Vanometric power cell"},
    {value : "Meat_Deer", text : "Venison"},
    {value : "VitalsMonitor", text : "Vitals monitor"},
    {value : "WakeUp", text : "Wake-up"},
    {value : "Apparel_WarMask", text : "War mask"},
    {value : "Apparel_WarVeil", text : "War veil"},
    {value : "Meat_Warg", text : "Warg meat"},
    {value : "Corpse_Warg", text : "Warg corpse"},
    {value : "Corpse_WildBoar", text : "Wild boar corpse"},
    {value : "Meat_Wolf_Timber", text : "Wolfmeat"},
    {value : "Leather_Wolf", text : "Wolfskin"},
    {value : "WoodLog", text : "Wood"},
    {value : "Wort", text : "Wort"},
    {value : "Yayo", text : "Yayo"},
    {value : "Meat_YorkshireTerrier", text : "Yorkshire terrier meat"},
    {value : "Corpse_YorkshireTerrier", text : "Yorkshire terrier corpse"},
];

export default DataFile;